name: Auto-Constructor

on:
  schedule:
    - cron: '0 22 * * *'  # 每天 UTC 22:00（台灣時間 06:00）
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: 手動觸發 CI 工作流
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/Private-Storge/Auto-Constructor/actions/workflows/ci.yml/dispatches \
              -d '{"ref":"main"}'